package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String comuna;
     private String region;
     private int idPersona;
     private String telefono;
     private Persona persona;
     private Set empresas = new HashSet(0);

    public Cliente() {
    }

    //Constructor
    public Cliente(String telefono, String com, String reg, int idPer) {
        this.telefono = telefono;
        this.comuna = com;
        this.region = reg;
        this.idPersona = idPer;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getComuna() {
        return comuna;
    }

    public String getRegion() {
        return region;
    }

    public int getIdPersona() {
        return idPersona;
    }

    public void setComuna(String comuna) {
        this.comuna = comuna;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
    
    public Persona getPersona(){
        return this.persona;
    }
    
    public void setPersona(Persona persona){
        this.persona = persona;
    }




}


