//Paquete
package modelo;

//Importaciones
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

    /**
     * Atributos de la Clase Cliente. Los ID tienen la finalidad de ser una
     * ayuda la programacion, debido a que son campos autogenerados por la base
     * de datos una vez ingresados.
     */
    private int idCliente;
    private int comunaId;
    private int idPersona;
    private String telefono;
    private Persona persona;
    private Comuna comuna;
    private Set empresas = new HashSet(0);

    /**
     * Constructor por defecto de la clase Cliente.
     */
    public Cliente() {
    }

    /**
     * Constructor con parámetros de la clase Cliente.
     *
     * @param telefono TELEFONO de Cliente.
     * @param idPer PERSONA_ID_PERSONA de Cliente.
     * @param com COMUNA_ID_COMUNA de Cliente.
     */
    public Cliente(String telefono, int idPer, int com) {
        this.telefono = telefono;
        this.idPersona = idPer;
        this.comunaId = com;
    }

    /**
     *
     * @return
     */
    public int getIdCliente() {
        return this.idCliente;
    }

    /**
     *
     * @param idCliente
     */
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    /**
     *
     * @return
     */
    public String getTelefono() {
        return this.telefono;
    }

    /**
     *
     * @param telefono
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     *
     * @return
     */
    public int getIdPersona() {
        return idPersona;
    }

    /**
     *
     * @param idPersona
     */
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    /**
     *
     * @return
     */
    public Set getEmpresas() {
        return this.empresas;
    }

    /**
     *
     * @param empresas
     */
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }

    /**
     *
     * @return
     */
    public Persona getPersona() {
        return this.persona;
    }

    /**
     *
     * @param persona
     */
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    /**
     *
     * @return
     */
    public int getComunaId() {
        return this.comunaId;
    }

    /**
     *
     * @param comunaId
     */
    public void setComunaId(int comunaId) {
        this.comunaId = comunaId;
    }

    /**
     *
     * @return
     */
    public Comuna getComuna() {
        return comuna;
    }

    /**
     *
     * @param comuna
     */
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    /**
     * Función toString de la clase Cliente.
     *
     * @return los atributos del objeto en formato de texto.
     */
    @Override
    public String toString() {
        return "Cliente{" + "idCliente=" + idCliente + ", comunaId=" + comunaId + ", idPersona=" + idPersona + ", telefono=" + telefono + ", persona=" + persona + ", comuna=" + comuna + ", empresas=" + empresas + '}';
    }
}


