package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comuna generated by hbm2java
 */
public class Comuna  implements java.io.Serializable {


     private int idComuna;
     private Region region;
     private String nombre;
     private Set clientes = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Comuna() {
    }

    public Comuna(int idComuna, Region region, String nombre) {
        this.idComuna = idComuna;
        this.region = region;
        this.nombre = nombre;
    }
    public Comuna(int idComuna, Region region, String nombre, Set clientes, Set empresas) {
       this.idComuna = idComuna;
       this.region = region;
       this.nombre = nombre;
       this.clientes = clientes;
       this.empresas = empresas;
    }
   
    public int getIdComuna() {
        return this.idComuna;
    }
    
    public void setIdComuna(int idComuna) {
        this.idComuna = idComuna;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
}


