package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private int idContrato;
     private Date fechaInicio;
     private Date fechaTermino;
     private Set empresas = new HashSet(0);

    public Contrato() {
    }

    public Contrato(Date fechaInicio, Date fechaTermino) {
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
    }
	
    public Contrato(int idContrato, Date fechaInicio, Date fechaTermino) {
        this.idContrato = idContrato;
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
    }
    public Contrato(int idContrato, Date fechaInicio, Date fechaTermino, Set empresas) {
       this.idContrato = idContrato;
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.empresas = empresas;
    }
   
    public int getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


