//Paquete
package modelo;

//Importaciones
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato implements java.io.Serializable {

    /**
     * Atributos de la clase Contrato.
     */
    private int idContrato;
    private Date fechaInicio;
    private Date fechaTermino;
    private Set empresas = new HashSet(0);

    /**
     * Constructor por defecto de la clase Contrato.
     */
    public Contrato() {
    }

    /**
     * Constructor con parámetros de la clase Contrato
     *
     * @param fechaInicio FECHA_INICIO de Contrato.
     * @param fechaTermino FECHA_TERMINO de Contrato
     */
    public Contrato(Date fechaInicio, Date fechaTermino) {
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
    }

    public int getIdContrato() {
        return this.idContrato;
    }

    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaTermino() {
        return this.fechaTermino;
    }

    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }

    public Set getEmpresas() {
        return this.empresas;
    }

    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }

    /**
     * Función toString de la clase Contrato.
     *
     * @return los atributos del objeto en formato de texto.
     */
    @Override
    public String toString() {
        return "Contrato{" + "idContrato=" + idContrato + ", fechaInicio=" + fechaInicio + ", fechaTermino=" + fechaTermino + ", empresas=" + empresas + '}';
    }

}

