//Paquete
package modelo;

//Importaciones
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

    /**
     * Atributos de la clase Empresa.Los ID tienen la finalidad de ser una ayuda
     * la programacion, debido a que son campos autogenerados por la base de
     * datos una vez ingresados.
     */
    private int idEmpresa;
    private String rut;
    private String nombreFantasia;
    private char estado;
    private Cliente cliente;
    private Comuna comuna;
    private Contrato contrato;
    private Set trabajadors = new HashSet(0);

    /**
     * Constructor por defecto de la clase Empresa.
     */
    public Empresa() {
    }

    /**
     * Constructor con parámetros de la clase Empresa.
     *
     * @param rut RUT de empresa.
     * @param nombreFantasia NOMBRE_FANTASIA de empresa.
     * @param estado ESTADO de empresa.
     */
    public Empresa(String rut, String nombreFantasia, char estado) {
        this.rut = rut;
        this.nombreFantasia = nombreFantasia;
        this.estado = estado;
    }

    /**
     *
     * @return
     */
    public int getIdEmpresa() {
        return this.idEmpresa;
    }

    /**
     *
     * @param idEmpresa
     */
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    /**
     *
     * @return
     */
    public Cliente getCliente() {
        return this.cliente;
    }

    /**
     *
     * @param cliente
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    /**
     *
     * @return
     */
    public Comuna getComuna() {
        return this.comuna;
    }

    /**
     *
     * @param comuna
     */
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    /**
     *
     * @return
     */
    public Contrato getContrato() {
        return this.contrato;
    }

    /**
     *
     * @param contrato
     */
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    /**
     *
     * @return
     */
    public String getRut() {
        return this.rut;
    }

    /**
     *
     * @param rut
     */
    public void setRut(String rut) {
        this.rut = rut;
    }

    /**
     *
     * @return
     */
    public String getNombreFantasia() {
        return this.nombreFantasia;
    }

    /**
     *
     * @param nombreFantasia
     */
    public void setNombreFantasia(String nombreFantasia) {
        this.nombreFantasia = nombreFantasia;
    }

    /**
     *
     * @return
     */
    public char getEstado() {
        return this.estado;
    }

    /**
     *
     * @param estado
     */
    public void setEstado(char estado) {
        this.estado = estado;
    }

    /**
     *
     * @return
     */
    public Set getTrabajadors() {
        return this.trabajadors;
    }

    /**
     *
     * @param trabajadors
     */
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }

    /**
     * Función toString de la clase Empresa.
     *
     * @return los atributos del objeto en formato de texto.
     */
    @Override
    public String toString() {
        return "" + nombreFantasia;
    }

}


