//Paquete
package modelo;

//Importaciones
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

    /**
     * Atributos de la clase Empresa.Los ID tienen la finalidad de ser una ayuda
     * la programacion, debido a que son campos autogenerados por la base de
     * datos una vez ingresados.
     */
    private int idEmpresa;
    private String rut;
    private String nombreFantasia;
    private char estado;
    private int idCliente;
    private int idContrato;
    private int idComuna;
    private Cliente cliente;
    private Comuna comuna;
    private Contrato contrato;
    private Set trabajadors = new HashSet(0);

    /**
     * Constructor por defecto de la clase Empresa.
     */
    public Empresa() {
    }

    /**
     * Constructor con parámetros de la clase Empresa.
     *
     * @param rut RUT de empresa.
     * @param nombreFantasia NOMBRE_FANTASIA de empresa.
     * @param estado ESTADO de empresa.
     * @param idCliente CLIENTE_ID_CLIENTE de empresa.
     * @param idContrato CONTRATO_ID_CONTRATO de empresa.
     * @param idComuna COMUNA_ID_COMUNA de empresa.
     */
    public Empresa(String rut, String nombreFantasia, char estado, int idCliente, int idContrato, int idComuna) {
        this.idCliente = idCliente;
        this.idComuna = idComuna;
        this.idContrato = idContrato;
        this.rut = rut;
        this.nombreFantasia = nombreFantasia;
        this.estado = estado;
    }

    public int getIdEmpresa() {
        return this.idEmpresa;
    }

    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Comuna getComuna() {
        return this.comuna;
    }

    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    public Contrato getContrato() {
        return this.contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public String getRut() {
        return this.rut;
    }

    public void setRut(String rut) {
        this.rut = rut;
    }

    public String getNombreFantasia() {
        return this.nombreFantasia;
    }

    public void setNombreFantasia(String nombreFantasia) {
        this.nombreFantasia = nombreFantasia;
    }

    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }

    public Set getTrabajadors() {
        return this.trabajadors;
    }

    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }

    public int getIdCliente() {
        return idCliente;
    }

    public int getIdContrato() {
        return idContrato;
    }

    public int getIdComuna() {
        return idComuna;
    }

    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }

    public void setIdComuna(int idComuna) {
        this.idComuna = idComuna;
    }

    /**
     * Función toString de la clase Empresa.
     *
     * @return los atributos del objeto en formato de texto.
     */
    @Override
    public String toString() {
        return "Empresa{" + "idEmpresa=" + idEmpresa + ", rut=" + rut + ", nombreFantasia=" + nombreFantasia + ", estado=" + estado + ", idCliente=" + idCliente + ", idContrato=" + idContrato + ", idComuna=" + idComuna + ", cliente=" + cliente + ", comuna=" + comuna + ", contrato=" + contrato + ", trabajadors=" + trabajadors + '}';
    }

}


