//Paquete
package modelo;

//Importaciones
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

    /**
     * Atributos de la clase Persona.Los ID tienen la finalidad de ser una ayuda
     * la programacion, debido a que son campos autogenerados por la base de
     * datos una vez ingresados.
     */
    private int idPersona;
    private Usuario usuario;
    private String run;
    private String nombres;
    private String appPaterno;
    private String appMaterno;
    private Set clientes = new HashSet(0);
    private Set trabajadors = new HashSet(0);

    /**
     * Constructor por defecto de la clase Persona
     */
    public Persona() {
    }

    /**
     * Constructor por defecto de la clase Persona.
     *
     * @param run RUN de Persona.
     * @param nombres NOMBRES de Persona.
     * @param appPaterno APP_PATERNO de Persona.
     * @param appMaterno APP_MATERNO de Persona.
     */
    public Persona(String run, String nombres, String appPaterno, String appMaterno) {
        this.run = run;
        this.nombres = nombres;
        this.appPaterno = appPaterno;
        this.appMaterno = appMaterno;
    }

    /**
     *
     * @return
     */
    public int getIdPersona() {
        return this.idPersona;
    }

    /**
     *
     * @param idPersona
     */
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    /**
     *
     * @return
     */
    public Usuario getUsuario() {
        return this.usuario;
    }

    /**
     *
     * @param usuario
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     *
     * @return
     */
    public String getRun() {
        return this.run;
    }

    /**
     *
     * @param run
     */
    public void setRun(String run) {
        this.run = run;
    }

    /**
     *
     * @return
     */
    public String getNombres() {
        return this.nombres;
    }

    /**
     *
     * @param nombres
     */
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    /**
     *
     * @return
     */
    public String getAppPaterno() {
        return this.appPaterno;
    }

    /**
     *
     * @param appPaterno
     */
    public void setAppPaterno(String appPaterno) {
        this.appPaterno = appPaterno;
    }

    /**
     *
     * @return
     */
    public String getAppMaterno() {
        return this.appMaterno;
    }

    /**
     *
     * @param appMaterno
     */
    public void setAppMaterno(String appMaterno) {
        this.appMaterno = appMaterno;
    }

    /**
     *
     * @return
     */
    public Set getClientes() {
        return this.clientes;
    }

    /**
     *
     * @param clientes
     */
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

    /**
     *
     * @return
     */
    public Set getTrabajadors() {
        return this.trabajadors;
    }

    /**
     *
     * @param trabajadors
     */
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }

    /**
     * Función toString de la clase Persona.
     *
     * @return los atributos del objeto en formato de texto.
     */
    @Override
    public String toString() {
        return "Persona{" + "idPersona=" + idPersona + ", usuario=" + usuario + ", run=" + run + ", nombres=" + nombres + ", appPaterno=" + appPaterno + ", appMaterno=" + appMaterno + ", clientes=" + clientes + ", trabajadors=" + trabajadors + '}';
    }

}

