package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private Usuario usuario;
     private String run;
     private String nombres;
     private String appPaterno;
     private String appMaterno;
     private int idUser;
     private Set clientes = new HashSet(0);
     private Set trabajadors = new HashSet(0);

    public Persona() {
    }

    public Persona(String run, String nombres, String appPaterno, String appMaterno, int idUser) {
        this.run = run;
        this.nombres = nombres;
        this.appPaterno = appPaterno;
        this.appMaterno = appMaterno;
    }
    
    public Persona(int idPersona, Usuario usuario, String run, String nombres, String appPaterno, String appMaterno, Set clientes, Set trabajadors) {
       this.idPersona = idPersona;
       this.usuario = usuario;
       this.run = run;
       this.nombres = nombres;
       this.appPaterno = appPaterno;
       this.appMaterno = appMaterno;
       this.clientes = clientes;
       this.trabajadors = trabajadors;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRun() {
        return this.run;
    }
    
    public void setRun(String run) {
        this.run = run;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getAppPaterno() {
        return this.appPaterno;
    }
    
    public void setAppPaterno(String appPaterno) {
        this.appPaterno = appPaterno;
    }
    public String getAppMaterno() {
        return this.appMaterno;
    }
    
    public void setAppMaterno(String appMaterno) {
        this.appMaterno = appMaterno;
    }
    
    public int getIdUser(){
        return this.idUser;
    }
    
    public void setIdUser(int idUser){
        this.idUser = idUser;
    }
    
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }

    @Override
    public String toString() {
        return "Persona{" + "idPersona=" + idPersona + ", usuario=" + usuario + ", run=" + run + ", nombres=" + nombres + ", appPaterno=" + appPaterno + ", appMaterno=" + appMaterno + ", idUser=" + idUser + ", clientes=" + clientes + ", trabajadors=" + trabajadors + '}';
    }




}


