package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private int idRegion;
     private String nombre;
     private Set comunas = new HashSet(0);

    public Region() {
    }

	
    public Region(int idRegion, String nombre) {
        this.idRegion = idRegion;
        this.nombre = nombre;
    }
    public Region(int idRegion, String nombre, Set comunas) {
       this.idRegion = idRegion;
       this.nombre = nombre;
       this.comunas = comunas;
    }
   
    public int getIdRegion() {
        return this.idRegion;
    }
    
    public void setIdRegion(int idRegion) {
        this.idRegion = idRegion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getComunas() {
        return this.comunas;
    }
    
    public void setComunas(Set comunas) {
        this.comunas = comunas;
    }
}


