//Paquete
package modelo;

//Importaciones
import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

    /**
     * Atributos de la clase Region.
     */
    private int idRegion;
    private String nombre;
    private Set comunas = new HashSet(0);

    /**
     * Constructor por defecto de la clase Region.
     */
    public Region() {
    }

    /**
     * Constructor con parámetros de la clase Region.
     *
     * @param idRegion ID_REGION de Region.
     * @param nombre NOMBRE de Region.
     */
    public Region(int idRegion, String nombre) {
        this.idRegion = idRegion;
        this.nombre = nombre;
    }

    /**
     *
     * @return
     */
    public int getIdRegion() {
        return this.idRegion;
    }

    /**
     *
     * @param idRegion
     */
    public void setIdRegion(int idRegion) {
        this.idRegion = idRegion;
    }

    /**
     *
     * @return
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     *
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     *
     * @return
     */
    public Set getComunas() {
        return this.comunas;
    }

    /**
     *
     * @param comunas
     */
    public void setComunas(Set comunas) {
        this.comunas = comunas;
    }

    /**
     * Función toString de la clase Region.
     *
     * @return los atributos del objeto en formato de texto.
     */
    @Override
    public String toString() {
        return "Region{" + "idRegion=" + idRegion + ", nombre=" + nombre + ", comunas=" + comunas + '}';
    }

}


