package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private TrabajadorId id;
     private Empresa empresa;
     private Persona persona;
     private String telefono;
     private Date fechaContrato;
     private String cargo;

    public Trabajador() {
    }

    public Trabajador(TrabajadorId id, Empresa empresa, Persona persona, String telefono, Date fechaContrato, String cargo) {
       this.id = id;
       this.empresa = empresa;
       this.persona = persona;
       this.telefono = telefono;
       this.fechaContrato = fechaContrato;
       this.cargo = cargo;
    }
   
    public TrabajadorId getId() {
        return this.id;
    }
    
    public void setId(TrabajadorId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaContrato() {
        return this.fechaContrato;
    }
    
    public void setFechaContrato(Date fechaContrato) {
        this.fechaContrato = fechaContrato;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }




}


