package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TrabajadorId generated by hbm2java
 */
public class TrabajadorId  implements java.io.Serializable {


     private BigDecimal idTrabajador;
     private BigDecimal empresaIdEmpresa;

    public TrabajadorId() {
    }

    public TrabajadorId(BigDecimal idTrabajador, BigDecimal empresaIdEmpresa) {
       this.idTrabajador = idTrabajador;
       this.empresaIdEmpresa = empresaIdEmpresa;
    }
   
    public BigDecimal getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(BigDecimal idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public BigDecimal getEmpresaIdEmpresa() {
        return this.empresaIdEmpresa;
    }
    
    public void setEmpresaIdEmpresa(BigDecimal empresaIdEmpresa) {
        this.empresaIdEmpresa = empresaIdEmpresa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrabajadorId) ) return false;
		 TrabajadorId castOther = ( TrabajadorId ) other; 
         
		 return ( (this.getIdTrabajador()==castOther.getIdTrabajador()) || ( this.getIdTrabajador()!=null && castOther.getIdTrabajador()!=null && this.getIdTrabajador().equals(castOther.getIdTrabajador()) ) )
 && ( (this.getEmpresaIdEmpresa()==castOther.getEmpresaIdEmpresa()) || ( this.getEmpresaIdEmpresa()!=null && castOther.getEmpresaIdEmpresa()!=null && this.getEmpresaIdEmpresa().equals(castOther.getEmpresaIdEmpresa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTrabajador() == null ? 0 : this.getIdTrabajador().hashCode() );
         result = 37 * result + ( getEmpresaIdEmpresa() == null ? 0 : this.getEmpresaIdEmpresa().hashCode() );
         return result;
   }   


}


