//Paquete
package modelo;

//Importaciones
import java.util.Date;

/**
 * Trabajador generated by hbm2java
 */
public class Trabajador implements java.io.Serializable {

    /**
     * Atributos de la clase Trabajador.
     */
    private int idTrabajador;
    private String telefono;
    private Date fechaContrato;
    private String cargo;
    private Empresa empresa;
    private Persona persona;

    /**
     * Constructor por defecto de la clase Trabajador.
     */
    public Trabajador() {
    }

    /**
     * Constructor con parámetros de la clase Trabajador.
     *
     * @param telefono TELEFONO de Trabajador.
     * @param fechaContrato FECHA_CONTRATO de Trabajador.
     * @param cargo CARGO de Trabajador.
     */
    public Trabajador(String telefono, Date fechaContrato, String cargo) {
        this.telefono = telefono;
        this.fechaContrato = fechaContrato;
        this.cargo = cargo;
    }

    /**
     *
     * @return
     */
    public int getIdTrabajador() {
        return this.idTrabajador;
    }

    /**
     *
     * @param idTrabajador
     */
    public void setIdTrabajador(int idTrabajador) {
        this.idTrabajador = idTrabajador;
    }

    /**
     *
     * @return
     */
    public String getTelefono() {
        return this.telefono;
    }

    /**
     *
     * @param telefono
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     *
     * @return
     */
    public Date getFechaContrato() {
        return this.fechaContrato;
    }

    /**
     *
     * @param fechaContrato
     */
    public void setFechaContrato(Date fechaContrato) {
        this.fechaContrato = fechaContrato;
    }

    /**
     *
     * @return
     */
    public String getCargo() {
        return this.cargo;
    }

    /**
     *
     * @param cargo
     */
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    /**
     *
     * @return
     */
    public Empresa getEmpresa() {
        return this.empresa;
    }

    /**
     *
     * @param empresa
     */
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    /**
     *
     * @return
     */
    public Persona getPersona() {
        return this.persona;
    }

    /**
     *
     * @param persona
     */
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    /**
     * Función toString de la clase Trabajador.
     *
     * @return los atributos del objeto en formato de texto.
     */
    @Override
    public String toString() {
        return "Trabajador{" + "idTrabajador=" + idTrabajador + ", telefono=" + telefono + ", fechaContrato=" + fechaContrato + ", cargo=" + cargo + ", empresa=" + empresa + ", persona=" + persona + '}';
    }

}
