package modelo;
// Generated 26-09-2018 15:18:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String username;
     private String clave;
     private String email;
     private int rol;
     private Set personas = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(String username, String clave, String email, int rol) {
        this.username = username;
        this.clave = clave;
        this.email = email;
        this.rol = rol;
    }
    
    public Usuario(int idUsuario, String username, String clave, String email, int rol) {
        this.idUsuario = idUsuario;
        this.username = username;
        this.clave = clave;
        this.email = email;
        this.rol = rol;
    }
    public Usuario(int idUsuario, String username, String clave, String email, int rol, Set personas) {
       this.idUsuario = idUsuario;
       this.username = username;
       this.clave = clave;
       this.email = email;
       this.rol = rol;
       this.personas = personas;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getRol() {
        return this.rol;
    }
    
    public void setRol(int rol) {
        this.rol = rol;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }

    @Override
    public String toString() {
        return "Usuario{" + "idUsuario=" + idUsuario + ", username=" + username + ", clave=" + clave + ", email=" + email + ", rol=" + rol + ", personas=" + personas + '}';
    }
    
    




}


