//Paquete
package presentacion;

//Importaciones
import com.sun.glass.events.KeyEvent;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Comuna;
import modelo.Persona;
import modelo.Region;
import modelo.Empresa;
import modelo.Trabajador;
import modelo.Usuario;
import negocio.NegCliente;
import negocio.NegComuna;
import negocio.NegEmpresa;
import negocio.NegPersona;
import negocio.NegTrabajador;
import negocio.NegUsuario;
import negocio.NegRegion;
import presentacion.validaciones.jTextFieldCharLimits;
import presentacion.validaciones.validadorCorreo;
import presentacion.validaciones.validadorRunChileno;

/**
 * @author Ignacio Antillanca
 * @version 1.3
 */
public class jdAddCuenta extends javax.swing.JDialog {

    /**
     * Variables utilizadas.
     */
    List<Comuna> listComuna;
    List<Region> listRegion;
    List<Empresa> listEmpresa;

    /**
     * Constructor que inicializa el modal del registro de cuentas.
     *
     * @param parent ventana jfPrincipal.
     * @param modal
     */
    public jdAddCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        limits();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 850, 600);
        this.setLocationRelativeTo(this);
        this.panelAdicionalDisable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddCuenta = new javax.swing.JPanel();
        pnlAddCuentaBanner = new javax.swing.JPanel();
        lblTituloCuenta = new javax.swing.JLabel();
        jpAddUsuario = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblPass2 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        ddlRol = new javax.swing.JComboBox<>();
        txtPass = new javax.swing.JPasswordField();
        txtPass2 = new javax.swing.JPasswordField();
        jpAddPersona = new javax.swing.JPanel();
        lblRun = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblAppPaterno = new javax.swing.JLabel();
        lblAppMaterno = new javax.swing.JLabel();
        txtRun = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtAppPaterno = new javax.swing.JTextField();
        txtAppMaterno = new javax.swing.JTextField();
        btnAgregarCuenta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jpAdicional = new javax.swing.JPanel();
        lblTelefono = new javax.swing.JLabel();
        lblComuna = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblFechaContra = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        ddlRegion = new javax.swing.JComboBox<>();
        ddlComuna = new javax.swing.JComboBox<>();
        txtCargo = new javax.swing.JTextField();
        lblIdEmp = new javax.swing.JLabel();
        ddlIdEmpresa = new javax.swing.JComboBox<>();
        dpFechaContrato = new com.toedter.calendar.JDateChooser();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlAddCuenta.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 4, true));
        pnlAddCuenta.setMaximumSize(null);
        pnlAddCuenta.setPreferredSize(new java.awt.Dimension(850, 600));

        pnlAddCuentaBanner.setBackground(new java.awt.Color(17, 48, 142));
        pnlAddCuentaBanner.setPreferredSize(new java.awt.Dimension(531, 68));

        lblTituloCuenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTituloCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCuenta.setText("REGISTRO DE NUEVA CUENTA DE USUARIO");

        javax.swing.GroupLayout pnlAddCuentaBannerLayout = new javax.swing.GroupLayout(pnlAddCuentaBanner);
        pnlAddCuentaBanner.setLayout(pnlAddCuentaBannerLayout);
        pnlAddCuentaBannerLayout.setHorizontalGroup(
            pnlAddCuentaBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddCuentaBannerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAddCuentaBannerLayout.setVerticalGroup(
            pnlAddCuentaBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCuentaBannerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTituloCuenta)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jpAddUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jpAddUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de Usuario"));

        lblUsername.setText("Nombre de Usuario");

        lblPass.setText("Contraseña");

        lblPass2.setText("Repita contraseña");

        lblCorreo.setText("Correo electronico");

        lblRol.setText("Rol");

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        ddlRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol", "Administrador", "Supervisor", "Cliente", "Trabajador", "Ingeniero", "Tecnico", "Medico" }));
        ddlRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAddUsuarioLayout = new javax.swing.GroupLayout(jpAddUsuario);
        jpAddUsuario.setLayout(jpAddUsuarioLayout);
        jpAddUsuarioLayout.setHorizontalGroup(
            jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddUsuarioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPass2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(txtPass2)
                    .addComponent(txtUsername))
                .addGap(95, 95, 95)
                .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ddlRol, 0, 143, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAddUsuarioLayout.setVerticalGroup(
            jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(lblCorreo)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol)
                    .addComponent(ddlRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAddUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass2)
                    .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpAddPersona.setBackground(new java.awt.Color(255, 255, 255));
        jpAddPersona.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de Persona"));

        lblRun.setText("Run");

        lblNombres.setText("Nombres");

        lblAppPaterno.setText("Apellido Paterno");
        lblAppPaterno.setMaximumSize(new java.awt.Dimension(80, 14));
        lblAppPaterno.setMinimumSize(new java.awt.Dimension(80, 14));
        lblAppPaterno.setPreferredSize(new java.awt.Dimension(80, 14));

        lblAppMaterno.setText("Apellido materno");

        txtRun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRunKeyTyped(evt);
            }
        });

        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresKeyTyped(evt);
            }
        });

        txtAppPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAppPaternoKeyTyped(evt);
            }
        });

        txtAppMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAppMaternoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpAddPersonaLayout = new javax.swing.GroupLayout(jpAddPersona);
        jpAddPersona.setLayout(jpAddPersonaLayout);
        jpAddPersonaLayout.setHorizontalGroup(
            jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAppMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAppPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRun)
                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtAppMaterno)
                    .addComponent(txtAppPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpAddPersonaLayout.setVerticalGroup(
            jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRun)
                    .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAppPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAddPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppMaterno)
                    .addComponent(txtAppMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAgregarCuenta.setBackground(new java.awt.Color(17, 48, 142));
        btnAgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCuenta.setText("REGISTRAR");
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(17, 42, 142));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jpAdicional.setBackground(new java.awt.Color(255, 255, 255));
        jpAdicional.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion Adicional"));

        lblTelefono.setText("Teléfono");

        lblComuna.setText("Comuna");

        lblRegion.setText("Region");

        lblCargo.setText("Cargo");

        lblFechaContra.setText("Fecha Contrato");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        ddlRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddlRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddlRegionItemStateChanged(evt);
            }
        });

        ddlComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCargoKeyTyped(evt);
            }
        });

        lblIdEmp.setText("Empresa");

        ddlIdEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpAdicionalLayout = new javax.swing.GroupLayout(jpAdicional);
        jpAdicional.setLayout(jpAdicionalLayout);
        jpAdicionalLayout.setHorizontalGroup(
            jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdicionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAdicionalLayout.createSequentialGroup()
                        .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAdicionalLayout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpAdicionalLayout.createSequentialGroup()
                                .addComponent(lblRegion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ddlRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(dpFechaContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpAdicionalLayout.createSequentialGroup()
                        .addComponent(lblComuna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ddlIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jpAdicionalLayout.setVerticalGroup(
            jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdicionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefono)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaContra))
                    .addComponent(dpFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(ddlRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCargo)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblComuna)
                    .addGroup(jpAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ddlComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIdEmp)
                        .addComponent(ddlIdEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(153, 153, 153));
        lblMensaje.setText("*Todos los campos son obligatorios");

        javax.swing.GroupLayout pnlAddCuentaLayout = new javax.swing.GroupLayout(pnlAddCuenta);
        pnlAddCuenta.setLayout(pnlAddCuentaLayout);
        pnlAddCuentaLayout.setHorizontalGroup(
            pnlAddCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddCuentaBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
            .addGroup(pnlAddCuentaLayout.createSequentialGroup()
                .addGroup(pnlAddCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddCuentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAddCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpAddUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlAddCuentaLayout.createSequentialGroup()
                                .addComponent(jpAddPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlAddCuentaLayout.createSequentialGroup()
                        .addGroup(pnlAddCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddCuentaLayout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(btnAgregarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAddCuentaLayout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(lblMensaje)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAddCuentaLayout.setVerticalGroup(
            pnlAddCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCuentaLayout.createSequentialGroup()
                .addComponent(pnlAddCuentaBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpAddPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAgregarCuenta))
                .addGap(13, 13, 13)
                .addComponent(lblMensaje)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAddCuenta.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que deshabilita el panel con la informacion adicional necesaria
     * para el registro de clientes o trabajadores
     */
    public void panelAdicionalDisable() {
        for (Component cp : this.jpAdicional.getComponents()) {
            cp.setEnabled(false);
        }
    }

    /**
     * Método que habilita el panel con la informacion adicional necesaria para
     * el registro de clientes o trabajadores
     */
    public void panelAdicionalEnable() {
        for (Component cp : this.jpAdicional.getComponents()) {
            cp.setEnabled(true);
        }
    }

    /**
     * Método que obtiene los datos ingresados en el formulario de cuenta de
     * usuario nueva y los envia a su respectivo controller.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ActionEvent)
     */
    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        if (!validateEmptys()) {
            if (validateDuplicate()) {
                try {
                    Usuario u = new Usuario();
                    u.setUsername(this.txtUsername.getText());
                    if (String.valueOf(this.txtPass.getPassword()).length() >= 6) {
                        if (String.valueOf(this.txtPass.getPassword()).equals(String.valueOf(this.txtPass2.getPassword()))) {
                            u.setClave(String.valueOf(this.txtPass.getPassword()));
                            if (new validadorCorreo(this.txtCorreo.getText()).validateEmail() == true) {
                                u.setEmail(this.txtCorreo.getText());
                                u.setRol(this.ddlRol.getSelectedIndex());
                                if (new validadorRunChileno(this.txtRun.getText()).validateRun() == true) {
                                    NegUsuario user = new NegUsuario();
                                    user.addUsuario(u);
                                    Persona p = new Persona();
                                    p.setRun(this.txtRun.getText());
                                    p.setNombres(this.txtNombres.getText());
                                    p.setAppPaterno(this.txtAppPaterno.getText());
                                    p.setAppMaterno(this.txtAppMaterno.getText());
                                    

                                    NegPersona per = new NegPersona();
                                    per.addPersona(p);
                                    switch (this.ddlRol.getSelectedIndex()) {
                                        case 3:
                                            Cliente cl = new Cliente();
                                            Comuna com = new Comuna();
                                            cl.setTelefono(this.txtTelefono.getText());
                                            cl.setComuna(com);
                                            com = (Comuna) this.ddlComuna.getModel().getSelectedItem();
                                            cl.getComuna().setIdComuna(com.getIdComuna());
                                            NegCliente neg = new NegCliente();
                                            neg.addCliente(cl);
                                            JOptionPane.showMessageDialog(rootPane, "Cuenta de Cliente registrada correctamente");
                                            this.dispose();
                                            break;
                                        case 4:
                                            Trabajador tr = new Trabajador();
                                            Empresa emp = new Empresa();
                                            tr.setTelefono(this.txtTelefono.getText());
                                            tr.setFechaContrato(this.dpFechaContrato.getDate());
                                            tr.setCargo(this.txtCargo.getText());
                                            tr.setEmpresa(emp);
                                            emp = (Empresa) this.ddlIdEmpresa.getModel().getSelectedItem();
                                            tr.getEmpresa().setIdEmpresa(emp.getIdEmpresa());
                                            NegTrabajador negT = new NegTrabajador();
                                            negT.addTrabajador(tr);
                                            JOptionPane.showMessageDialog(rootPane, "Cuenta de Trabajador registrada correctamente");
                                            this.dispose();
                                            break;
                                        default:
                                            JOptionPane.showMessageDialog(rootPane, "Cuenta de usuario registrada correctamente");
                                            this.dispose();
                                            break;
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "El RUN ingresado no es valido.", "", JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "El formato del correo es incorrecto", "", JOptionPane.ERROR_MESSAGE);
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "La contraseña debe tener mínimo 6 caracteres", "", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (HeadlessException e) {
                    JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado", "", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAgregarCuentaActionPerformed

    /**
     * Método que valida que los campos del formulario de usuario no esten
     * vacios.
     *
     * @return campo true/false
     */
    private boolean validateEmptys() {
        boolean campo = this.txtUsername.getText().isEmpty();
        campo |= this.txtPass.getText().isEmpty();
        campo |= this.txtPass2.getText().isEmpty();
        campo |= this.txtCorreo.getText().isEmpty();
        campo |= this.ddlRol.getSelectedIndex() == 0;
        campo |= this.txtRun.getText().isEmpty();
        campo |= this.txtNombres.getText().isEmpty();
        campo |= this.txtAppPaterno.getText().isEmpty();
        campo |= this.txtAppMaterno.getText().isEmpty();
        if (this.ddlRol.getSelectedIndex() == 3) {
            campo |= this.txtTelefono.getText().isEmpty();
            campo |= this.ddlRegion.getSelectedIndex() == 0;
            campo |= this.ddlComuna.getSelectedIndex() == 0;
        } else if (this.ddlRol.getSelectedIndex() == 4) {
            campo |= this.txtTelefono.getText().isEmpty();
            campo |= this.dpFechaContrato.getDate() == null;
            campo |= this.txtCargo.getText().isEmpty();
            campo |= this.ddlIdEmpresa.getSelectedIndex() == 0;
        }
        return campo;
    }

    /**
     * Accion del boton "CANCELAR" del modal de registro de cuenta. Termina el
     * proceso cerrando la ventana emergente.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ActionEvent)
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Método que modifica el formulario de registro de cuenta en el caso que el
     * tipo de cuenta sea cliente o trabajador.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ActionEvent)
     */
    private void ddlRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlRolActionPerformed
        switch (this.ddlRol.getSelectedIndex()) {
            case 3:
                panelAdicionalEnable();
                this.dpFechaContrato.setEnabled(false);
                this.txtCargo.setEnabled(false);
                this.ddlIdEmpresa.setEnabled(false);
                break;
            case 4:
                panelAdicionalEnable();
                this.ddlComuna.setEnabled(false);
                this.ddlRegion.setEnabled(false);
                break;
            default:
                panelAdicionalDisable();
                break;
        }
    }//GEN-LAST:event_ddlRolActionPerformed

    /**
     * Método que realiza la carga de los jcombobox al momento de mostrar la
     * ventana.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ActionEvent)
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        NegRegion negR = new NegRegion();
        NegComuna negC = new NegComuna();
        NegEmpresa negE = new NegEmpresa();

        DefaultComboBoxModel cModelR = (DefaultComboBoxModel) this.ddlRegion.getModel();

        cModelR.removeAllElements();
        this.ddlComuna.removeAllItems();
        this.ddlIdEmpresa.removeAllItems();

        cModelR.addElement("Región...");
        this.ddlComuna.addItem("Comuna...");
        this.ddlIdEmpresa.addItem("Empresa...");
        try {
            listRegion = negR.getAllRegion();
            listComuna = negC.getAllComuna();
            listEmpresa = negE.getAllEmpresa();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error inesperado (combobox)");
        }

        for (Region r : listRegion) {
            cModelR.addElement(r.getNombre());
        }

        for (Comuna c : listComuna) {
            Comuna cm = new Comuna();
            cm.setNombre(c.getNombre());
            cm.setIdComuna(c.getIdComuna());
            this.ddlComuna.addItem(cm);
        }

        for (Empresa e : listEmpresa) {
            Empresa em = new Empresa();
            em.setIdEmpresa(e.getIdEmpresa());
            em.setNombreFantasia(e.getNombreFantasia());
            this.ddlIdEmpresa.addItem(em);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * Metodo que filtra las comunas en base a la region seleccionada.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ItemEvent)
     */
    private void ddlRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddlRegionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.ddlRegion.getSelectedIndex() > 0) {
                NegComuna negC = new NegComuna();
                
                this.ddlComuna.removeAllItems();
                this.ddlComuna.addItem("Comuna...");
                try {
                    listComuna = negC.getAllComuna();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error con la actualizacion de comunas.");
                }
                for (Comuna c : listComuna) {
                    if (c.getRegion().getIdRegion() == this.ddlRegion.getSelectedIndex()) {
                        Comuna cm = new Comuna();
                        cm.setNombre(c.getNombre());
                        cm.setIdComuna(c.getIdComuna());
                        this.ddlComuna.addItem(cm);
                    }
                }
            }
        }
    }//GEN-LAST:event_ddlRegionItemStateChanged

    /**
     * Función que evita escribir caracteres diferentes a números, en el campos
     * de ingreso del RUN.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtRunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRunKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (int)c == 75 || (int)c == 107)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRunKeyTyped

    /**
     * Función que evita escribir caracteres numericos o simbolos, en el campo
     * de nombres.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE || c == 39)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombresKeyTyped

    /**
     * Función que evita escribir caracteres numericos o simbolos, en el campo
     * de apellido paterno.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtAppPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAppPaternoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE || c == 39)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAppPaternoKeyTyped

    /**
     * Función que evita escribir caracteres numericos o simbolos, en el campo
     * de apellido materno.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtAppMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAppMaternoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE || c == 39)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAppMaternoKeyTyped
    /**
     * Función que evita escribir caracteres diferentes a números, en el campo
     * de ingreso de Teléfono.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * Función que evita escribir caracteres numericos o simbolos, en el campo
     * de cargo.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCargoKeyTyped

    /**
     * Función que evita escribir caracteres especiales o letra Ñ-ñ en el campo
     * de nombre de usuario.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        char c = evt.getKeyChar();
        if (!(((int) c >= 65 && (int) c <= 90) || ((int) c >= 97 && (int) c <= 122) || Character.isDigit(c) || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtUsernameKeyTyped

    /**
     * Método que verifica que el nombre de usuario o run ingresado, no se
     * encuentren ya registrados.
     *
     * @return true o false, si algún campo ya se encuentra registrado.
     */
    public boolean validateDuplicate() {
        String txtUser = this.txtUsername.getText();
        String txtRunPer = this.txtRun.getText();
        NegUsuario negU = new NegUsuario();
        NegPersona negP = new NegPersona();
        if (negU.validateUsername(txtUser) != null) {
            JOptionPane.showMessageDialog(null, "Ya existe registrado ese nombre de usuario, ingrese otro...", "", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (negP.validateRun(txtRunPer) != null) {
            JOptionPane.showMessageDialog(null, "Ya existe registrado ese RUN de persona, ingrese otro...", "", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    /**
     * Método que establece los limites de caracteres por campos de texto en el
     * formulario.
     *
     */
    public void limits() {
        this.txtUsername.setDocument(new jTextFieldCharLimits(20));
        this.txtPass.setDocument(new jTextFieldCharLimits(20));
        this.txtPass2.setDocument(new jTextFieldCharLimits(20));
        this.txtCorreo.setDocument(new jTextFieldCharLimits(40));
        this.txtRun.setDocument(new jTextFieldCharLimits(9));
        this.txtNombres.setDocument(new jTextFieldCharLimits(40));
        this.txtAppPaterno.setDocument(new jTextFieldCharLimits(20));
        this.txtAppMaterno.setDocument(new jTextFieldCharLimits(20));
        this.txtTelefono.setDocument(new jTextFieldCharLimits(9));
        this.txtCargo.setDocument(new jTextFieldCharLimits(20));
        Date fechaActual = new Date();
        this.dpFechaContrato.setMaxSelectableDate(fechaActual);
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String fechaT = "01/01/1975";
            Date fechaMaxima = sdf.parse(fechaT);
            this.dpFechaContrato.setMinSelectableDate(fechaMaxima);
        } catch (ParseException ex) {
        }
        JTextFieldDateEditor editor = (JTextFieldDateEditor) this.dpFechaContrato.getDateEditor();
        editor.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<Object> ddlComuna;
    private javax.swing.JComboBox<Object> ddlIdEmpresa;
    private javax.swing.JComboBox<String> ddlRegion;
    private javax.swing.JComboBox<String> ddlRol;
    private com.toedter.calendar.JDateChooser dpFechaContrato;
    private javax.swing.JPanel jpAddPersona;
    private javax.swing.JPanel jpAddUsuario;
    private javax.swing.JPanel jpAdicional;
    private javax.swing.JLabel lblAppMaterno;
    private javax.swing.JLabel lblAppPaterno;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFechaContra;
    private javax.swing.JLabel lblIdEmp;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblRun;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloCuenta;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlAddCuenta;
    private javax.swing.JPanel pnlAddCuentaBanner;
    private javax.swing.JTextField txtAppMaterno;
    private javax.swing.JTextField txtAppPaterno;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtRun;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
