//Paquete
package presentacion;

//Importaciones
import com.sun.glass.events.KeyEvent;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.event.ItemEvent;
import java.beans.PropertyChangeEvent;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Comuna;
import modelo.Contrato;
import modelo.Empresa;
import modelo.Region;
import negocio.NegCliente;
import negocio.NegComuna;
import negocio.NegContrato;
import negocio.NegEmpresa;
import negocio.NegRegion;
import presentacion.validaciones.jTextFieldCharLimits;
import presentacion.validaciones.validadorRunChileno;

/**
 * @author Ignacio Antillanca
 * @version 1.0
 */
public class jdUpEmpresa extends javax.swing.JDialog {

    /**
     * Variables utilizadas.
     */
    List<Comuna> listComuna;
    List<Region> listRegion;
    List<Cliente> listCliente;
    Empresa empresa;

    /**
     * Constructor que inicializa la ventana de ingreso de empresa.
     *
     * @param parent ventana jfPrincipal
     * @param modal
     */
    public jdUpEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        initComponents();
        limits();
        this.dpFechaInicio.getDateEditor().addPropertyChangeListener((PropertyChangeEvent e) -> {
            if (this.dpFechaInicio.getDate() == null) {
            } else {
                Date fecha = this.dpFechaInicio.getDate();
                int dias = 365;
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(fecha);
                calendar.add(Calendar.DAY_OF_YEAR, dias);
                dpFechaTermino.setDate(calendar.getTime());
            }
        });
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 850, 550);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUpEmpresa = new javax.swing.JPanel();
        pnlAddEmpresaBanner = new javax.swing.JPanel();
        lblTituloEmpresa = new javax.swing.JLabel();
        lblIdContrato = new javax.swing.JLabel();
        lblIdEmpresa = new javax.swing.JLabel();
        jpAddContrato = new javax.swing.JPanel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaTermino = new javax.swing.JLabel();
        dpFechaInicio = new com.toedter.calendar.JDateChooser();
        dpFechaTermino = new com.toedter.calendar.JDateChooser();
        jpAddEmpresa = new javax.swing.JPanel();
        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        lblNombFantasia = new javax.swing.JLabel();
        txtNombreFantasia = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        ddlCliente = new javax.swing.JComboBox<>();
        lblRegion = new javax.swing.JLabel();
        ddlRegion = new javax.swing.JComboBox<>();
        lblComuna = new javax.swing.JLabel();
        ddlComuna = new javax.swing.JComboBox<>();
        btnUpEmpresa = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlUpEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        pnlUpEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 4, true));
        pnlUpEmpresa.setMaximumSize(null);
        pnlUpEmpresa.setPreferredSize(new java.awt.Dimension(850, 550));

        pnlAddEmpresaBanner.setBackground(new java.awt.Color(17, 48, 142));
        pnlAddEmpresaBanner.setPreferredSize(new java.awt.Dimension(842, 72));

        lblTituloEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTituloEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloEmpresa.setText("MODIFICACION DE EMPRESA");

        lblIdContrato.setBackground(new java.awt.Color(17, 48, 142));
        lblIdContrato.setForeground(new java.awt.Color(17, 48, 142));
        lblIdContrato.setText("ID CONTRATO");

        lblIdEmpresa.setBackground(new java.awt.Color(17, 48, 142));
        lblIdEmpresa.setForeground(new java.awt.Color(17, 48, 142));
        lblIdEmpresa.setText("ID EMPRESA");

        javax.swing.GroupLayout pnlAddEmpresaBannerLayout = new javax.swing.GroupLayout(pnlAddEmpresaBanner);
        pnlAddEmpresaBanner.setLayout(pnlAddEmpresaBannerLayout);
        pnlAddEmpresaBannerLayout.setHorizontalGroup(
            pnlAddEmpresaBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEmpresaBannerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlAddEmpresaBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIdEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(lblTituloEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAddEmpresaBannerLayout.setVerticalGroup(
            pnlAddEmpresaBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddEmpresaBannerLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(pnlAddEmpresaBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloEmpresa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdContrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdEmpresa))
        );

        jpAddContrato.setBackground(new java.awt.Color(255, 255, 255));
        jpAddContrato.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de Contrato"));

        lblFechaInicio.setText("Fecha de Inicio");

        lblFechaTermino.setText("Fecha de Termino");

        javax.swing.GroupLayout jpAddContratoLayout = new javax.swing.GroupLayout(jpAddContrato);
        jpAddContrato.setLayout(jpAddContratoLayout);
        jpAddContratoLayout.setHorizontalGroup(
            jpAddContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddContratoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblFechaInicio)
                .addGap(84, 84, 84)
                .addComponent(dpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(lblFechaTermino)
                .addGap(46, 46, 46)
                .addComponent(dpFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAddContratoLayout.setVerticalGroup(
            jpAddContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddContratoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpAddContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dpFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaTermino)
                    .addGroup(jpAddContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaInicio)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jpAddEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        jpAddEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de Empresa"));

        lblRut.setText("Rut");

        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });

        lblNombFantasia.setText("Nombre Fantasía");

        txtNombreFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreFantasiaKeyTyped(evt);
            }
        });

        lblCliente.setText("Cliente");

        lblRegion.setText("Región");

        ddlRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ddlRegionItemStateChanged(evt);
            }
        });

        lblComuna.setText("Comuna");

        javax.swing.GroupLayout jpAddEmpresaLayout = new javax.swing.GroupLayout(jpAddEmpresa);
        jpAddEmpresa.setLayout(jpAddEmpresaLayout);
        jpAddEmpresaLayout.setHorizontalGroup(
            jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddEmpresaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRut)
                    .addComponent(lblNombFantasia)
                    .addComponent(lblCliente))
                .addGap(76, 76, 76)
                .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRut)
                    .addComponent(txtNombreFantasia)
                    .addComponent(ddlCliente, 0, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegion)
                    .addComponent(lblComuna))
                .addGap(92, 92, 92)
                .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ddlComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAddEmpresaLayout.setVerticalGroup(
            jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAddEmpresaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegion)
                    .addComponent(ddlRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAddEmpresaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComuna)
                            .addComponent(ddlComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAddEmpresaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombFantasia))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAddEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(ddlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        btnUpEmpresa.setBackground(new java.awt.Color(17, 48, 142));
        btnUpEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnUpEmpresa.setText("MODIFICAR");
        btnUpEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpEmpresaActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(17, 48, 142));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(153, 153, 153));
        lblMensaje.setText("*Todos los campos son obligatorios");

        javax.swing.GroupLayout pnlUpEmpresaLayout = new javax.swing.GroupLayout(pnlUpEmpresa);
        pnlUpEmpresa.setLayout(pnlUpEmpresaLayout);
        pnlUpEmpresaLayout.setHorizontalGroup(
            pnlUpEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpEmpresaLayout.createSequentialGroup()
                .addComponent(pnlAddEmpresaBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlUpEmpresaLayout.createSequentialGroup()
                .addGroup(pnlUpEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpEmpresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUpEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpAddContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpAddEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlUpEmpresaLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(btnUpEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpEmpresaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMensaje)
                .addGap(322, 322, 322))
        );
        pnlUpEmpresaLayout.setVerticalGroup(
            pnlUpEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpEmpresaLayout.createSequentialGroup()
                .addComponent(pnlAddEmpresaBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jpAddContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpAddEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlUpEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpEmpresa)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUpEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUpEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que evita escribir caracteres diferentes a números, en el campo de
     * RUT.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (int) c == 75 || (int) c == 107)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRutKeyTyped

    /**
     * Evento que impde escribir caracters o numeros en el campo de nombre de
     * fantasia de la empresa.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (KeyEvent)
     */
    private void txtNombreFantasiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreFantasiaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreFantasiaKeyTyped

    /**
     * Evento que realiza la recargar del combobox de comuna, dependiente la
     * region selecionada.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ItemEvent)
     */
    private void ddlRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ddlRegionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.ddlRegion.getSelectedIndex() > 0) {
                NegComuna negC = new NegComuna();

                this.ddlComuna.removeAllItems();
                this.ddlComuna.addItem("Comuna...");
                try {
                    listComuna = negC.getAllComuna();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error con la actualizacion de comunas.");
                }
                for (Comuna c : listComuna) {
                    if (c.getRegion().getIdRegion() == this.ddlRegion.getSelectedIndex()) {
                        Comuna cm = new Comuna();
                        cm.setNombre(c.getNombre());
                        cm.setIdComuna(c.getIdComuna());
                        this.ddlComuna.addItem(cm);
                    }
                }
            }
        }
    }//GEN-LAST:event_ddlRegionItemStateChanged

    /**
     * Método que realiza la llamada al metodo correspondiente, para cagar la
     * informacion y modificarla.
     *
     * @param id1 ID de Empresa
     * @param id2 ID de Contrato
     */
    public void cargaDeCampos(int id1, int id2) {
        NegEmpresa negE = new NegEmpresa();
        Empresa emp = negE.obtenerEmpresa(id2);
        //Lleando ID empresa, contrato
        this.lblIdContrato.setText(String.valueOf(emp.getContrato().getIdContrato()));
        this.lblIdEmpresa.setText(String.valueOf(emp.getIdEmpresa()));
        //Llenado informacion contrato
        this.dpFechaInicio.setDate(emp.getContrato().getFechaInicio());
        this.dpFechaTermino.setDate(emp.getContrato().getFechaTermino());
        //Llenado informacion empresa
        this.txtRut.setText(emp.getRut());
        this.txtNombreFantasia.setText(emp.getNombreFantasia());
        DefaultComboBoxModel modelCliente = (DefaultComboBoxModel) this.ddlCliente.getModel();
        DefaultComboBoxModel modelRegion = (DefaultComboBoxModel) this.ddlRegion.getModel();
        DefaultComboBoxModel modelComuna = (DefaultComboBoxModel) this.ddlComuna.getModel();
        modelCliente.setSelectedItem(emp.getCliente().getPersona().getNombres() + " " + emp.getCliente().getPersona().getAppPaterno()+ " " + emp.getCliente().getPersona().getAppMaterno());
        modelRegion.setSelectedItem(emp.getComuna().getRegion().getNombre());
        modelComuna.setSelectedItem(emp.getComuna().getNombre());
        //Asignacion de empresa a cargar, a variable temporal.
        empresa = emp;
    }

    /**
     * Método que recibe la informacion modificada en el formulario de
     * actualizacion de empresa y la envia al controlador.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ActionEvent)
     */
    private void btnUpEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpEmpresaActionPerformed

        if (!validateEmptys()) {
            if (validateDuplicateRut()) {
                try {
                    Contrato c = new Contrato();
                    c.setIdContrato(Integer.parseInt(this.lblIdContrato.getText()));
                    c.setFechaInicio(this.dpFechaInicio.getDate());
                    c.setFechaTermino(this.dpFechaTermino.getDate());
                    NegContrato contrato = new NegContrato();
                    contrato.upContrato(c);

                    Empresa e = new Empresa();
                    Comuna com = new Comuna();
                    Cliente cli = new Cliente();
                    if (new validadorRunChileno(this.txtRut.getText()).validateRun() == true) {
                        e.setIdEmpresa(Integer.parseInt(this.lblIdEmpresa.getText()));
                        e.setRut(this.txtRut.getText());
                        e.setNombreFantasia(this.txtNombreFantasia.getText());
                        e.setEstado('1');
                        e.setCliente(cli);
                        e.getCliente().setIdCliente(this.ddlCliente.getSelectedIndex());
                        e.setContrato(c);
                        e.getContrato().setIdContrato(Integer.parseInt(this.lblIdContrato.getText()));
                        e.setComuna(com);
                        e.getComuna().setIdComuna(this.ddlComuna.getSelectedIndex());
                        NegEmpresa negE = new NegEmpresa();
                        negE.upEmpresa(e);

                        JOptionPane.showMessageDialog(rootPane, "Empresa modificada correctamente");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "El RUT ingresado es invalido", "", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error inesperado" + ex.toString());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios", "", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnUpEmpresaActionPerformed

    /**
     * Método que valida que los campos del formulario de registro de empresa no
     * se encuentren vacios.
     *
     * @return campo true/false.
     */
    private boolean validateEmptys() {
        boolean campo = this.dpFechaInicio.getDate() == null;
        campo |= this.dpFechaTermino.getDate() == null;
        campo |= this.txtRut.getText().isEmpty();
        campo |= this.txtNombreFantasia.getText().isEmpty();
        campo |= this.ddlCliente.getSelectedIndex() == 0;
        campo |= this.ddlRegion.getSelectedIndex() == 0;
        campo |= this.ddlComuna.getSelectedIndex() == 0;
        return campo;
    }

    /**
     * Método que establece los limites de caracteres por campo de texto en el
     * formulario de registro de empresa.
     *
     */
    public void limits() {
        Date fechaInicio = new Date();
        this.dpFechaInicio.setMinSelectableDate(fechaInicio);
        
        this.txtRut.setDocument(new jTextFieldCharLimits(9));
        this.txtNombreFantasia.setDocument(new jTextFieldCharLimits(30));
        this.dpFechaTermino.setEnabled(false);

        JTextFieldDateEditor editor = (JTextFieldDateEditor) this.dpFechaInicio.getDateEditor();
        JTextFieldDateEditor editor2 = (JTextFieldDateEditor) this.dpFechaTermino.getDateEditor();
        editor.setEditable(false);
        editor2.setEditable(false);
    }
    
    /**
     * 
     * @return 
     */
    public boolean validateDuplicateRut(){
        String rut = this.txtRut.getText();
        NegEmpresa emp = new NegEmpresa();
        if (emp.validateDuplicateRut(rut) != null && !empresa.getRut().equals(rut)) {
            JOptionPane.showMessageDialog(null, "Ya existe registrado ese RUN de Empresa, ingrese otro...", "", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        } 
    }

    /**
     * Evento que cierra la ventana de ingreso de empresa (Cancelar)
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ActionEvent)
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Evento que carga al momento de abrir la ventana y permite la carga de los
     * combobox a utilizar (Clientes, Regiones, Comúnas).
     *
     * @param evt evento que indica que se realizo una accion definida
     * (WindowEvent)
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        NegRegion negR = new NegRegion();
        NegComuna negC = new NegComuna();
        NegCliente negCl = new NegCliente();

        DefaultComboBoxModel cModelR = (DefaultComboBoxModel) this.ddlRegion.getModel();
        DefaultComboBoxModel cModelC = (DefaultComboBoxModel) this.ddlCliente.getModel();
        DefaultComboBoxModel cModelCm = (DefaultComboBoxModel) this.ddlComuna.getModel();

        cModelR.addElement("Región...");
        cModelCm.addElement("Comuna...");
        cModelC.addElement("Cliente...");
        try {
            listRegion = negR.getAllRegion();
            listComuna = negC.getAllComuna();
            listCliente = negCl.getAllCliente();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error inesperado (combobox)");
        }

        for (Region r : listRegion) {
            cModelR.addElement(r.getNombre());
        }

        for (Comuna c : listComuna) {
            cModelCm.addElement(c.getNombre());
        }

        for (Cliente c : listCliente) {
            cModelC.addElement(c.getPersona().getNombres() +" "+ c.getPersona().getAppPaterno() +" "+ c.getPersona().getAppMaterno());
        }
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnUpEmpresa;
    private javax.swing.JComboBox<Object> ddlCliente;
    private javax.swing.JComboBox<Object> ddlComuna;
    private javax.swing.JComboBox<Object> ddlRegion;
    private com.toedter.calendar.JDateChooser dpFechaInicio;
    private com.toedter.calendar.JDateChooser dpFechaTermino;
    private javax.swing.JPanel jpAddContrato;
    private javax.swing.JPanel jpAddEmpresa;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaTermino;
    private javax.swing.JLabel lblIdContrato;
    private javax.swing.JLabel lblIdEmpresa;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombFantasia;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTituloEmpresa;
    private javax.swing.JPanel pnlAddEmpresaBanner;
    private javax.swing.JPanel pnlUpEmpresa;
    private javax.swing.JTextField txtNombreFantasia;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
