//Paquete
package presentacion;

//Importaciones
import java.awt.Cursor;
import modelo.Persona;
import negocio.NegLogin;
import negocio.NegPersona;

/**
 * @author Ignacio Antillanca
 * @version 18/09/2018 v1.0
 */
public class jfLogin extends javax.swing.JFrame {

    /**
     * Constructor por defecto de jfLogin.
     */
    public jfLogin() {
        this.setUndecorated(true); // variable para ocultar herramientas de ventana
        initComponents();
        this.setLocationRelativeTo(null); // variable para posicionar la ventana al centro del monitor.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        piClose = new org.edisoncor.gui.panel.PanelImage();
        piUsername = new org.edisoncor.gui.panel.PanelImage();
        piPassword = new org.edisoncor.gui.panel.PanelImage();
        lblDerechos = new javax.swing.JLabel();
        piLogo = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 48, 142), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 330));
        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblTitulo.setText("INGRESO SISTEMA ADMINISTRATIVO");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(60, 180, 350, 22);

        txtUser.setToolTipText("Nombre de Usuario");
        txtUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 48, 142), 1, true));
        jPanel1.add(txtUser);
        txtUser.setBounds(140, 240, 190, 30);

        txtPass.setToolTipText("Contraseña");
        txtPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(17, 48, 142), 1, true));
        jPanel1.add(txtPass);
        txtPass.setBounds(140, 290, 190, 30);

        btnLogin.setBackground(new java.awt.Color(17, 48, 142));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("ENTRAR");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(160, 350, 130, 30);

        piClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/close_icon.png"))); // NOI18N
        piClose.setPreferredSize(new java.awt.Dimension(30, 30));
        piClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piCloseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout piCloseLayout = new javax.swing.GroupLayout(piClose);
        piClose.setLayout(piCloseLayout);
        piCloseLayout.setHorizontalGroup(
            piCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        piCloseLayout.setVerticalGroup(
            piCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(piClose);
        piClose.setBounds(410, 10, 30, 30);

        piUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/user_icon.png"))); // NOI18N
        piUsername.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout piUsernameLayout = new javax.swing.GroupLayout(piUsername);
        piUsername.setLayout(piUsernameLayout);
        piUsernameLayout.setHorizontalGroup(
            piUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        piUsernameLayout.setVerticalGroup(
            piUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(piUsername);
        piUsername.setBounds(90, 240, 30, 30);

        piPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/pass_icon.png"))); // NOI18N

        javax.swing.GroupLayout piPasswordLayout = new javax.swing.GroupLayout(piPassword);
        piPassword.setLayout(piPasswordLayout);
        piPasswordLayout.setHorizontalGroup(
            piPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        piPasswordLayout.setVerticalGroup(
            piPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(piPassword);
        piPassword.setBounds(90, 290, 30, 30);

        lblDerechos.setForeground(new java.awt.Color(153, 153, 153));
        lblDerechos.setText("Sistema Administrativo SAFE - 2018 - Todos los derechos reservados (C).");
        jPanel1.add(lblDerechos);
        lblDerechos.setBounds(20, 430, 410, 14);

        piLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/logo_full.png"))); // NOI18N

        javax.swing.GroupLayout piLogoLayout = new javax.swing.GroupLayout(piLogo);
        piLogo.setLayout(piLogoLayout);
        piLogoLayout.setHorizontalGroup(
            piLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        piLogoLayout.setVerticalGroup(
            piLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(piLogo);
        piLogo.setBounds(110, 30, 220, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método de evento que cierra el proceso de login al posicionar el mouse
     * sobre la imagen.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (MouseEvent)
     */
    private void piCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_piCloseMouseClicked

    /**
     * Método que envía las credenciales ingresadas al controlador para ser
     * verificadas y otorgar el acceso o no, dependendieo la respuesta obtenida.
     *
     * @param evt evento que indica que se realizo una accion definida
     * (ActionEvent)
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String password = new String(txtPass.getPassword());
        boolean permiso = NegLogin.Login(txtUser.getText(), password);
        Persona persona = new NegPersona().obtenerPersona2(txtUser.getText());

        if (permiso) {
            this.dispose();
            jfPrincipal nueva = new jfPrincipal(persona);
            nueva.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * Cambia el icono del cursor cuando entra sobre el icono de cierre del 
     * login.
     * @param evt evento que indica que se realizo una accion definida
     * (MouseEvent)
     */
    private void piCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piCloseMouseEntered
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_piCloseMouseEntered

    /**
     * Cambia el icono del cursor cuando sale sobre el icono de cierre del
     * login.
     * @param evt evento que indica que se realizo una accion definida
     * (MouseEvent)
     */
    private void piCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piCloseMouseExited
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_piCloseMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDerechos;
    private javax.swing.JLabel lblTitulo;
    private org.edisoncor.gui.panel.PanelImage piClose;
    private org.edisoncor.gui.panel.PanelImage piLogo;
    private org.edisoncor.gui.panel.PanelImage piPassword;
    private org.edisoncor.gui.panel.PanelImage piUsername;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
