//Paquete
package presentacion;

//Importaciones
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empresa;
import modelo.Persona;
import negocio.NegEmpresa;
import negocio.NegPersona;
import rojerusan.RSPanelsSlider;

/**
 * @author Igncio Antillanca
 * @version 1.1
 */
public class jfPrincipal extends javax.swing.JFrame {
    

    /**
     * Constructor por defecto de jfPrincipal.
     */
    public jfPrincipal() {
        this.setUndecorated(true);
        initComponents();
        addJTableCuentas();
        addJTableEmpresas();
        // Variables para adapatar la pantalla inicial al centro y 
        // con tamaño 950x600 sin importar la resolucion del monitor
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 950, 500); 
        this.setLocationRelativeTo(this); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        btnEmpresa = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnCuentas = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        piLogout = new org.edisoncor.gui.panel.PanelImage();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        jpInicio = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        lblContratos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();
        jpCuentas = new javax.swing.JPanel();
        lblCuentas = new javax.swing.JLabel();
        btnEliminarCuenta = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        piSearchIcon = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCuentas = new org.jdesktop.swingx.JXTable();
        btnAgregarCuenta = new javax.swing.JButton();
        btnModificarCuenta = new javax.swing.JButton();
        btnVerCuenta = new javax.swing.JButton();
        jpEmpresas = new javax.swing.JPanel();
        lblEmpresas = new javax.swing.JLabel();
        btnAgregarEmpresa = new javax.swing.JButton();
        piIconSearch1 = new org.edisoncor.gui.panel.PanelImage();
        txtSearch2 = new javax.swing.JTextField();
        btnModificarEmpresa = new javax.swing.JButton();
        btnEliminarEmpresa = new javax.swing.JButton();
        btnVerEmpresa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmpresa = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(0, 590));

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpPrincipal.setName(""); // NOI18N
        jpPrincipal.setPreferredSize(new java.awt.Dimension(800, 600));

        jpMenu.setBackground(new java.awt.Color(17, 48, 142));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpresa.setBackground(new java.awt.Color(17, 48, 142));
        btnEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpresa.setText("GESTION DE EMPRESAS");
        btnEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmpresa.setContentAreaFilled(false);
        btnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresaActionPerformed(evt);
            }
        });
        jpMenu.add(btnEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 30));

        btnInicio.setBackground(new java.awt.Color(17, 48, 142));
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.setContentAreaFilled(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jpMenu.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 30));

        btnCuentas.setBackground(new java.awt.Color(17, 48, 142));
        btnCuentas.setForeground(new java.awt.Color(255, 255, 255));
        btnCuentas.setText("GESTION DE CUENTAS");
        btnCuentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCuentas.setContentAreaFilled(false);
        btnCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasActionPerformed(evt);
            }
        });
        jpMenu.add(btnCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 30));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jpMenu.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 120));

        piLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/logout_icon.png"))); // NOI18N
        piLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout piLogoutLayout = new javax.swing.GroupLayout(piLogout);
        piLogout.setLayout(piLogoutLayout);
        piLogoutLayout.setHorizontalGroup(
            piLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        piLogoutLayout.setVerticalGroup(
            piLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jpMenu.add(piLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 60, 60));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        jpInicio.setBackground(new java.awt.Color(255, 255, 255));
        jpInicio.setName("jpInicio"); // NOI18N
        jpInicio.setLayout(null);

        lblInicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblInicio.setText("BIENVENIDO ADMINISTRADOR");
        jpInicio.add(lblInicio);
        lblInicio.setBounds(290, 30, 220, 17);

        lblInfo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblInfo.setText("Informacion general:");
        jpInicio.add(lblInfo);
        lblInfo.setBounds(110, 290, 160, 15);

        lblContratos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblContratos.setText("Contratos activos:");
        jpInicio.add(lblContratos);
        lblContratos.setBounds(110, 130, 160, 15);

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        jpInicio.add(jScrollPane1);
        jScrollPane1.setBounds(210, 330, 380, 100);

        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblContratos);

        jpInicio.add(jScrollPane2);
        jScrollPane2.setBounds(210, 160, 380, 100);

        rSPanelsSlider1.add(jpInicio, "card2");

        jpCuentas.setBackground(new java.awt.Color(255, 255, 255));
        jpCuentas.setName("jpCuentas"); // NOI18N
        jpCuentas.setLayout(null);

        lblCuentas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCuentas.setText("Gestion de Cuentas de Usuarios");
        jpCuentas.add(lblCuentas);
        lblCuentas.setBounds(230, 10, 280, 17);

        btnEliminarCuenta.setBackground(new java.awt.Color(17, 48, 142));
        btnEliminarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCuenta.setText("ELIMINAR");
        jpCuentas.add(btnEliminarCuenta);
        btnEliminarCuenta.setBounds(240, 132, 110, 23);
        jpCuentas.add(txtSearch);
        txtSearch.setBounds(546, 132, 200, 20);

        piSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/search_icon.png"))); // NOI18N
        piSearchIcon.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout piSearchIconLayout = new javax.swing.GroupLayout(piSearchIcon);
        piSearchIcon.setLayout(piSearchIconLayout);
        piSearchIconLayout.setHorizontalGroup(
            piSearchIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        piSearchIconLayout.setVerticalGroup(
            piSearchIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jpCuentas.add(piSearchIcon);
        piSearchIcon.setBounds(520, 132, 20, 20);

        tblCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID USUARIO", "NOMBRE PERSONA", "RUN", "ROL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCuentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tblCuentas);
        if (tblCuentas.getColumnModel().getColumnCount() > 0) {
            tblCuentas.getColumnModel().getColumn(0).setResizable(false);
            tblCuentas.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblCuentas.getColumnModel().getColumn(1).setResizable(false);
            tblCuentas.getColumnModel().getColumn(1).setPreferredWidth(15);
            tblCuentas.getColumnModel().getColumn(2).setResizable(false);
            tblCuentas.getColumnModel().getColumn(2).setPreferredWidth(10);
            tblCuentas.getColumnModel().getColumn(3).setResizable(false);
            tblCuentas.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jpCuentas.add(jScrollPane5);
        jScrollPane5.setBounds(2, 160, 750, 280);

        btnAgregarCuenta.setBackground(new java.awt.Color(17, 48, 142));
        btnAgregarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCuenta.setText("AGREGAR");
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });
        jpCuentas.add(btnAgregarCuenta);
        btnAgregarCuenta.setBounds(0, 132, 110, 23);

        btnModificarCuenta.setBackground(new java.awt.Color(17, 48, 142));
        btnModificarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarCuenta.setText("MODIFICAR");
        btnModificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCuentaActionPerformed(evt);
            }
        });
        jpCuentas.add(btnModificarCuenta);
        btnModificarCuenta.setBounds(120, 132, 110, 23);

        btnVerCuenta.setBackground(new java.awt.Color(17, 48, 142));
        btnVerCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnVerCuenta.setText("VER");
        btnVerCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCuentaActionPerformed(evt);
            }
        });
        jpCuentas.add(btnVerCuenta);
        btnVerCuenta.setBounds(360, 132, 110, 23);

        rSPanelsSlider1.add(jpCuentas, "card3");

        jpEmpresas.setBackground(new java.awt.Color(255, 255, 255));
        jpEmpresas.setName("jpEmpresas"); // NOI18N
        jpEmpresas.setLayout(null);

        lblEmpresas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmpresas.setText("Gestion de Contratos y Empresas");
        jpEmpresas.add(lblEmpresas);
        lblEmpresas.setBounds(240, 10, 260, 17);

        btnAgregarEmpresa.setBackground(new java.awt.Color(17, 48, 142));
        btnAgregarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarEmpresa.setText("AGREGAR");
        btnAgregarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEmpresaActionPerformed(evt);
            }
        });
        jpEmpresas.add(btnAgregarEmpresa);
        btnAgregarEmpresa.setBounds(0, 132, 110, 23);

        piIconSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/img/search_icon.png"))); // NOI18N
        piIconSearch1.setMaximumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout piIconSearch1Layout = new javax.swing.GroupLayout(piIconSearch1);
        piIconSearch1.setLayout(piIconSearch1Layout);
        piIconSearch1Layout.setHorizontalGroup(
            piIconSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        piIconSearch1Layout.setVerticalGroup(
            piIconSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jpEmpresas.add(piIconSearch1);
        piIconSearch1.setBounds(520, 132, 20, 20);
        jpEmpresas.add(txtSearch2);
        txtSearch2.setBounds(546, 132, 200, 20);

        btnModificarEmpresa.setBackground(new java.awt.Color(17, 48, 142));
        btnModificarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarEmpresa.setText("MODIFICAR");
        btnModificarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEmpresaActionPerformed(evt);
            }
        });
        jpEmpresas.add(btnModificarEmpresa);
        btnModificarEmpresa.setBounds(120, 132, 110, 23);

        btnEliminarEmpresa.setBackground(new java.awt.Color(17, 48, 142));
        btnEliminarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpresa.setText("ELIMINAR");
        jpEmpresas.add(btnEliminarEmpresa);
        btnEliminarEmpresa.setBounds(240, 132, 110, 23);

        btnVerEmpresa.setBackground(new java.awt.Color(17, 42, 148));
        btnVerEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEmpresa.setText("VER");
        btnVerEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEmpresaActionPerformed(evt);
            }
        });
        jpEmpresas.add(btnVerEmpresa);
        btnVerEmpresa.setBounds(360, 132, 110, 23);

        tblEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID EMPRESA", "NOMBRE EMPRESA", "NOMBRE CLIENTE", "ID CONTRATO", "FECHA INICIO", "FECHA TERMINO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEmpresa);

        jpEmpresas.add(jScrollPane3);
        jScrollPane3.setBounds(0, 160, 750, 280);

        rSPanelsSlider1.add(jpEmpresas, "card4");

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que mueve hacia vista de GESTION DE CUENTAS y oculta las otras por
     * el PanelSlider.
     * @param evt evento que indica que se realizo una accion definida (ActionEvent)
     */
    private void btnCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasActionPerformed
        if (!this.btnCuentas.isSelected()) {
            this.btnInicio.setSelected(false);
            this.btnCuentas.setSelected(true);
            this.btnEmpresa.setSelected(false);
            
            rSPanelsSlider1.setPanelSlider(20,jpCuentas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnCuentasActionPerformed

    /**
     * Método que mueve hacia vista de INICIO y oculta las otras por
     * el PanelSlider.
     * @param evt evento que indica que se realizo una accion definida (ActionEvent)
     */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if (!this.btnInicio.isSelected()) {
            this.btnInicio.setSelected(true);
            this.btnCuentas.setSelected(false);
            this.btnEmpresa.setSelected(false);
            
            rSPanelsSlider1.setPanelSlider(20,jpInicio, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * Método que mueve hacia vista de GESTION DE EMPRESA y oculta las otras por
     * el PanelSlider.
     * @param evt evento que indica que se realizo una accion definida (ActionEvent)
     */
    private void btnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresaActionPerformed
        if (!this.btnEmpresa.isSelected()) {
            this.btnInicio.setSelected(false);
            this.btnCuentas.setSelected(false);
            this.btnEmpresa.setSelected(true);
            
            rSPanelsSlider1.setPanelSlider(20,jpEmpresas, RSPanelsSlider.DIRECT.RIGHT);
        }
    }//GEN-LAST:event_btnEmpresaActionPerformed

    /**
     * Método de evento que cierra el proceso de login al posicionar el mouse
     * sobre la imagen.
     * @param evt evento que indica que se realizo una accion definida (MouseEvent)
     */
    private void piLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piLogoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_piLogoutMouseClicked

    /**
     * Método que invoca el modal de jdAddEmpresa y lo hace visible.
     * 
     * @param evt evento que indica que se realizo una accion definida (ActionEvent)
     */
    private void btnAgregarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpresaActionPerformed
        jdAddEmpresa ventana = new jdAddEmpresa(this, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAgregarEmpresaActionPerformed

    /**
     * Método que invoca el modal de jdAddCuenta y lo hace visible.
     * 
     * @param evt evento que indica que se realizo una accion definida (ActionEvent)
     */
    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        jdAddCuenta ventana = new jdAddCuenta(this, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed

    /**
     * Método que recibe la id del item de la tabla cuenta y abre la ventana de
     * modificaciones de datos en base a esa id.
     *
     * @param evt evento que indica que se realizo una accion definida (ActionEvent)
     */
    private void btnModificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCuentaActionPerformed
        try {
            int column = 0;
            int row = this.tblCuentas.getSelectedRow();
            //Valor del ID de usuario
            int value = (Integer) this.tblCuentas.getModel().getValueAt(row, column);
            
            int column2 = 3;
            //Valor del ID de rol
            int value2;
            String rol = (String)this.tblCuentas.getModel().getValueAt(row, column2);
            switch (rol) {
                case "Administrador":
                    value2 = 1;
                    break;
                case "Supervisor":
                    value2 = 2;
                    break;
                case "Cliente":
                    value2 = 3;
                    break;
                case "Trabajador":
                    value2 = 4;
                    break;
                case "Ingeniero":
                    value2 = 5;
                    break;
                case "Técnico":
                    value2 = 6;
                    break;
                default:
                    value2 = 7;
                    break;
            }
            jdUpCuenta ventana = new jdUpCuenta(this, true);
            ventana.cargaDeCampos(value, value2);
            ventana.setVisible(true);
            //System.out.println("ID USER: " + value + " ID ROL: " + value2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Seleccione un item de la tabla...", "", JOptionPane.ERROR_MESSAGE);
        }
        //System.out.println("ID: " + value);
    }//GEN-LAST:event_btnModificarCuentaActionPerformed

    /**
     * Método que invoca el modal de modificacion de empresa y lo hace visible.
     * 
     * @param evt evento que indica que se realizo una accion definida (ActionEvent)
     */
    private void btnModificarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEmpresaActionPerformed
         try {
            int row = this.tblEmpresa.getSelectedRow();
            int column = 0;
            //Valor del ID de Empresa
            int idEmp = (Integer) this.tblEmpresa.getModel().getValueAt(row, column);
            int column2 = 3;
            //Valor del ID de Contrato
            int idCon = (Integer) this.tblEmpresa.getModel().getValueAt(row, column2);
          
            jdUpEmpresa ventana = new jdUpEmpresa(this, true);
            ventana.cargaDeCampos(idEmp, idCon);
            ventana.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Seleccione un item de la tabla..." + ex.toString(), "", JOptionPane.ERROR_MESSAGE);
        }
        //System.out.println("ID: " + value);
    }//GEN-LAST:event_btnModificarEmpresaActionPerformed

    /**
     * Método que invoca el modal de ver cuentas y lo hace visible
     * @param evt 
     */
    private void btnVerCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCuentaActionPerformed
        try {
            int column = 0;
            int row = this.tblCuentas.getSelectedRow();
            //Valor del ID de usuario
            int value = (Integer) this.tblCuentas.getModel().getValueAt(row, column);
            
            int column2 = 3;
            //Valor del ID de rol
            int value2;
            String rol = (String)this.tblCuentas.getModel().getValueAt(row, column2);
            switch (rol) {
                case "Administrador":
                    value2 = 1;
                    break;
                case "Supervisor":
                    value2 = 2;
                    break;
                case "Cliente":
                    value2 = 3;
                    break;
                case "Trabajador":
                    value2 = 4;
                    break;
                case "Ingeniero":
                    value2 = 5;
                    break;
                case "Técnico":
                    value2 = 6;
                    break;
                default:
                    value2 = 7;
                    break;
            }
            jdVerCuenta ventana = new jdVerCuenta(this, true);
            ventana.cargaDeCampos(value, value2);
            ventana.setVisible(true);
            //System.out.println("ID USER: " + value + " ID ROL: " + value2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Seleccione un item de la tabla...", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerCuentaActionPerformed

    /**
     * Método que invoca el modal de ver cuentas y lo hace visible
     * @param evt 
     */
    private void btnVerEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEmpresaActionPerformed
         try {
            int row = this.tblEmpresa.getSelectedRow();
            int column = 0;
            //Valor del ID de Empresa
            int idEmp = (Integer) this.tblEmpresa.getModel().getValueAt(row, column);
            int column2 = 3;
            //Valor del ID de Contrato
            int idCon = (Integer) this.tblEmpresa.getModel().getValueAt(row, column2);
          
            jdVerEmpresa ventana = new jdVerEmpresa(this, true);
            ventana.cargaDeCampos(idEmp, idCon);
            ventana.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Seleccione un item de la tabla..." + ex.toString(), "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVerEmpresaActionPerformed

    /**
     * Método que realiza el llenado de la tabla de cuentas con la información
     * de las personas.
     */
    public void addJTableCuentas(){
        DefaultTableModel model = (DefaultTableModel)this.tblCuentas.getModel();
        NegPersona negPer = new NegPersona();
        try {
          List<Persona> list = negPer.getAllPersona();  
          Object rowData[] = new Object[5];
            for (int i = 0; i < list.size(); i++) {
                rowData[0] = list.get(i).getUsuario().getIdUsuario();
                rowData[1] = list.get(i).getNombres() +" "+ list.get(i).getAppPaterno();
                rowData[2] = list.get(i).getRun();
              switch (list.get(i).getUsuario().getRol()) {
                  case 1:
                      rowData[3] = "Administrador";
                      break;
                  case 2:
                      rowData[3] = "Supervisor";
                      break;
                  case 3:
                      rowData[3] = "Cliente";
                      break;
                  case 4:
                      rowData[3] = "Trabajador";
                      break;
                  case 5:
                      rowData[3] = "Ingeniero";
                      break;
                  case 6:
                      rowData[3] = "Técnico";
                      break;
                  case 7:
                      rowData[3] = "Médico";
                      break;
                  default:
                      rowData[3] = "Otro";
                      break;
              }
              model.addRow(rowData);
            }
        } catch(Exception ex) {
            System.out.println("ERROR: " + ex.toString());
        }
    }
    
    /**
     * Método que realiza el llenado de la tabla de empresas con la información
     * de empresas y su contrato.
     */
    public void addJTableEmpresas() {
        DefaultTableModel model = (DefaultTableModel) this.tblEmpresa.getModel();
        NegEmpresa negEmp = new NegEmpresa();
        try {
            List<Empresa> list = negEmp.getAllEmpresa();
            Object rowData[] = new Object[6];
            for (int i = 0; i < list.size(); i++) {
                rowData[0] = list.get(i).getIdEmpresa();
                rowData[1] = list.get(i).getNombreFantasia();
                rowData[2] = list.get(i).getCliente().getPersona().getNombres() + list.get(i).getCliente().getPersona().getAppPaterno();
                rowData[3] = list.get(i).getContrato().getIdContrato();
                rowData[4] = list.get(i).getContrato().getFechaInicio();
                rowData[5] = list.get(i).getContrato().getFechaTermino();

                model.addRow(rowData);
            }
        } catch (Exception ex) {
            System.out.println("ERROR: " + ex.toString());
        }
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnAgregarEmpresa;
    private javax.swing.JButton btnCuentas;
    private javax.swing.JButton btnEliminarCuenta;
    private javax.swing.JButton btnEliminarEmpresa;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnModificarCuenta;
    private javax.swing.JButton btnModificarEmpresa;
    private javax.swing.JButton btnVerCuenta;
    private javax.swing.JButton btnVerEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jpCuentas;
    private javax.swing.JPanel jpEmpresas;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JLabel lblContratos;
    private javax.swing.JLabel lblCuentas;
    private javax.swing.JLabel lblEmpresas;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInicio;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage piIconSearch1;
    private org.edisoncor.gui.panel.PanelImage piLogout;
    private org.edisoncor.gui.panel.PanelImage piSearchIcon;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTable tblContratos;
    private org.jdesktop.swingx.JXTable tblCuentas;
    private org.jdesktop.swingx.JXTable tblEmpresa;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch2;
    // End of variables declaration//GEN-END:variables
}
